Repository shipshapecode/tether, pull requests merged in 2019-09, with the labels that each got.

#308 Add `allowPositionFixed` optimization option
  .browserslistrc
  dist/css/tether-theme-arrows.css
  dist/css/tether-theme-arrows.min.css
  dist/js/tether.esm.js
  dist/js/tether.esm.js.map
  dist/js/tether.esm.min.js
  dist/js/tether.esm.min.js.map
  dist/js/tether.js
  dist/js/tether.js.map
  dist/js/tether.min.js
  dist/js/tether.min.js.map
  src/js/tether.js
Labels: enhancement

#309 Return `this` in Evented class for easy chaining
  dist/js/tether.esm.js
  dist/js/tether.esm.js.map
  dist/js/tether.esm.min.js
  dist/js/tether.esm.min.js.map
  dist/js/tether.js
  dist/js/tether.js.map
  dist/js/tether.min.js
  dist/js/tether.min.js.map
  src/js/evented.js
  test/unit/evented.spec.js
Labels: enhancement

#310 Move class utils to a utils file, drop IE9 support
  .browserslistrc
  .travis.yml
  dist/js/tether.esm.js
  dist/js/tether.esm.js.map
  dist/js/tether.esm.min.js
  dist/js/tether.esm.min.js.map
  dist/js/tether.js
  dist/js/tether.js.map
  dist/js/tether.min.js
  dist/js/tether.min.js.map
  src/js/abutment.js
  src/js/constraint.js
  src/js/tether.js
  src/js/utils.js
  src/js/utils/classes.js
Labels: breaking

#311 Remove dist from git
  .gitignore
  .travis.yml
  dist/css/tether-theme-arrows-dark.css
  dist/css/tether-theme-arrows-dark.min.css
  dist/css/tether-theme-arrows.css
  dist/css/tether-theme-arrows.min.css
  dist/css/tether-theme-basic.css
  dist/css/tether-theme-basic.min.css
  dist/css/tether.css
  dist/css/tether.min.css
  dist/js/tether.esm.js
  dist/js/tether.esm.js.map
  dist/js/tether.esm.min.js
  dist/js/tether.esm.min.js.map
  dist/js/tether.js
  dist/js/tether.js.map
  dist/js/tether.min.js
  dist/js/tether.min.js.map
Labels: breaking

#315 Move deferred utils to their own file
  jest.config.js
  src/js/abutment.js
  src/js/constraint.js
  src/js/tether.js
  src/js/utils.js
  src/js/utils/deferred.js
  test/unit/deferred.spec.js
Labels: enhancement

#317 Refactor rollup config, add tests for pin and out-of-bounds
  rollup.config.js
  test/cypress/integration/out-of-bounds.spec.js
  test/cypress/integration/pin.spec.js
  test/unit/classes.spec.js
  test/unit/deferred.spec.js
Labels: enhancement

#318 Move offset to utils, add tests, test getClass
  src/js/tether.js
  src/js/utils/offset.js
  test/unit/tether.spec.js
  test/unit/utils/classes.spec.js
  test/unit/utils/deferred.spec.js
  test/unit/utils/offset.spec.js
Labels: enhancement

#319 More offset utils and tests
  src/js/tether.js
  src/js/utils/offset.js
  test/unit/utils/offset.spec.js
Labels: enhancement

#325 Split out some utils
  src/js/abutment.js
  src/js/constraint.js
  src/js/tether.js
  src/js/utils.js
  src/js/utils/bounds.js
  src/js/utils/general.js
Labels: enhancement

#328 Move TetherBase and use imports
  src/js/abutment.js
  src/js/constraint.js
  src/js/shift.js
  src/js/tether.js
  src/js/utils/general.js
  src/js/utils/parents.js
Labels: enhancement

#329 Remove classes when set to false
  src/js/tether.js
  test/unit/tether.spec.js
Labels: bug

#330 Add test for fixed anchoring on scroll
  test/cypress/integration/scroll.spec.js
Labels: internal

#331 Document events
  docs/intro.md
Labels: documentation

#333 Use type-check utils instead of typeof
  src/js/constraint.js
  src/js/evented.js
  src/js/shift.js
  src/js/tether.js
  src/js/utils/bounds.js
  src/js/utils/offset.js
  src/js/utils/parents.js
  src/js/utils/type-check.js
Labels: enhancement
